module soap_server_backup {
  interface IControllerCopySecurity {
    typedef sequence<octet> streamBytes;
    struct SongDTO {
      long id;
      string artist;
      string title;
      string type;
      long sizeMB;
      streamBytes arrayBytes;
    };
    boolean saveCopySong(in SongDTO objSong);
  };
};
