package corba_server_backup;


/**
* corba_server_backup/IControllerCopySecurityHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Tuesday, August 2, 2022 3:54:53 PM COT
*/

abstract public class IControllerCopySecurityHelper
{
  private static String  _id = "IDL:corba_server_backup/IControllerCopySecurity:1.0";

  public static void insert (org.omg.CORBA.Any a, corba_server_backup.IControllerCopySecurity that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static corba_server_backup.IControllerCopySecurity extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (corba_server_backup.IControllerCopySecurityHelper.id (), "IControllerCopySecurity");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static corba_server_backup.IControllerCopySecurity read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_IControllerCopySecurityStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, corba_server_backup.IControllerCopySecurity value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static corba_server_backup.IControllerCopySecurity narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba_server_backup.IControllerCopySecurity)
      return (corba_server_backup.IControllerCopySecurity)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba_server_backup._IControllerCopySecurityStub stub = new corba_server_backup._IControllerCopySecurityStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static corba_server_backup.IControllerCopySecurity unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof corba_server_backup.IControllerCopySecurity)
      return (corba_server_backup.IControllerCopySecurity)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      corba_server_backup._IControllerCopySecurityStub stub = new corba_server_backup._IControllerCopySecurityStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
