package corba_server_backup;


/**
* corba_server_backup/IControllerCopySecurity.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Tuesday, August 2, 2022 3:54:53 PM COT
*/

public interface IControllerCopySecurity extends IControllerCopySecurityOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IControllerCopySecurity
