package corba_server_backup;


/**
* corba_server_backup/IControllerCopySecurityOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Tuesday, August 2, 2022 3:54:53 PM COT
*/

public interface IControllerCopySecurityOperations 
{
  boolean saveCopySong (corba_server_backup.IControllerCopySecurityPackage.SongDTO objSong);
} // interface IControllerCopySecurityOperations
