package corba_server_backup.IControllerCopySecurityPackage;


/**
* corba_server_backup/IControllerCopySecurityPackage/SongDTO.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Tuesday, August 2, 2022 3:54:53 PM COT
*/

public final class SongDTO implements org.omg.CORBA.portable.IDLEntity
{
  public int id = (int)0;
  public String artist = null;
  public String title = null;
  public String type = null;
  public int sizeMB = (int)0;
  public org.omg.CORBA.Any arrayBytes[] = null;

  public SongDTO ()
  {
  } // ctor

  public SongDTO (int _id, String _artist, String _title, String _type, int _sizeMB, org.omg.CORBA.Any[] _arrayBytes)
  {
    id = _id;
    artist = _artist;
    title = _title;
    type = _type;
    sizeMB = _sizeMB;
    arrayBytes = _arrayBytes;
  } // ctor

} // class SongDTO
