package corba_server_backup.IControllerCopySecurityPackage;

/**
* corba_server_backup/IControllerCopySecurityPackage/SongDTOHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IServerBackup.idl
* Tuesday, August 2, 2022 3:54:53 PM COT
*/

public final class SongDTOHolder implements org.omg.CORBA.portable.Streamable
{
  public corba_server_backup.IControllerCopySecurityPackage.SongDTO value = null;

  public SongDTOHolder ()
  {
  }

  public SongDTOHolder (corba_server_backup.IControllerCopySecurityPackage.SongDTO initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = corba_server_backup.IControllerCopySecurityPackage.SongDTOHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    corba_server_backup.IControllerCopySecurityPackage.SongDTOHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return corba_server_backup.IControllerCopySecurityPackage.SongDTOHelper.type ();
  }

}
